### PR TITLE
chore: issue templates

### PR DESCRIPTION
**Pull request by megatank58**

### CODE REVIEW

**Comment by apoorvcodes** [comment]
Looks great to me!

**Comment by apoorvcodes** [comment]
What do you think @savioxavier

**Comment by savioxavier** [comment]
Looks alright to me. I might add a  `config.yml` file in a later PR to further improve pull-requesting experience.

**Comment by megatank58** [comment]
I am actually already working on converting this to issue forms along with the config.yml

**Comment by megatank58** [comment]
I am actually already working on converting this to issue forms along with the config.yml

**Pull request merged**
