### PR TITLE
release: v1.0.0

### PR DESCRIPTION
**Pull request by apoorvcodes**
This is final pr with all the fixes and touches there may be some bugs but this is the base version-1 guys thanks to all the contributors for this amazing accomplishment @jfontan , @booleanrecep , @savioxavier , @Panquesito7 @Shubhaankar-Sharma , @megatank58 , @scientific-dev .

### CODE REVIEW

**Comment by savioxavier** [comment]
Good to see we're fianlly ready for v1! 🎉 

Make sure you run `go fmt .` and `golangci-lint run .`, there are a few formatting fixes and linting to be done.

**Review by savioxavier — APPROVED** [review]
Should be good to go!

**Comment by apoorvcodes** [comment]
Yepp!

**Comment by savioxavier** [comment]
Going to wait for @megatank58's approval.

Also, all further PR's including this, should be squashed and merged.

**Pull request merged**
